[package]
name = "template_editor"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
dirs = "5.0.1"
eframe = "0.30.0"
egui = "0.30.0"
egui_dnd = "0.11.0"
serde_json = "1.0.134"
